services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Sync code for development
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env file

networks:
  default:
    driver: bridge

