# Generated by Django 4.2.16 on 2024-09-21 18:21

import datasender.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year of the weather data.', validators=[datasender.models.validate_year])),
                ('month', models.IntegerField(db_index=True, help_text='Month of the weather data (1-12).', validators=[datasender.models.validate_month])),
                ('dynamic_data', models.JSONField(blank=True, help_text='Dynamic weather data in key-value pairs.', null=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
