# Generated by Django 4.2.16 on 2024-09-19 21:16

import datasender.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year of the weather data.', validators=[datasender.models.validate_year])),
                ('month', models.IntegerField(db_index=True, help_text='Month of the weather data (1-12).', validators=[datasender.models.validate_month])),
                ('value', models.FloatField(blank=True, help_text='Measured value for the weather metric.', null=True)),
            ],
            options={
                'verbose_name': 'Min Temperature',
                'verbose_name_plural': 'Min Temperatures',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Tmean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year of the weather data.', validators=[datasender.models.validate_year])),
                ('month', models.IntegerField(db_index=True, help_text='Month of the weather data (1-12).', validators=[datasender.models.validate_month])),
                ('value', models.FloatField(blank=True, help_text='Measured value for the weather metric.', null=True)),
            ],
            options={
                'verbose_name': 'Mean Temperature',
                'verbose_name_plural': 'Mean Temperatures',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Tmax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year of the weather data.', validators=[datasender.models.validate_year])),
                ('month', models.IntegerField(db_index=True, help_text='Month of the weather data (1-12).', validators=[datasender.models.validate_month])),
                ('value', models.FloatField(blank=True, help_text='Measured value for the weather metric.', null=True)),
            ],
            options={
                'verbose_name': 'Max Temperature',
                'verbose_name_plural': 'Max Temperatures',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Sunshine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year of the weather data.', validators=[datasender.models.validate_year])),
                ('month', models.IntegerField(db_index=True, help_text='Month of the weather data (1-12).', validators=[datasender.models.validate_month])),
                ('value', models.FloatField(blank=True, help_text='Measured value for the weather metric.', null=True)),
            ],
            options={
                'verbose_name': 'Sunshine',
                'verbose_name_plural': 'Sunshines',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year of the weather data.', validators=[datasender.models.validate_year])),
                ('month', models.IntegerField(db_index=True, help_text='Month of the weather data (1-12).', validators=[datasender.models.validate_month])),
                ('value', models.FloatField(blank=True, help_text='Measured value for the weather metric.', null=True)),
            ],
            options={
                'verbose_name': 'Rainfall',
                'verbose_name_plural': 'Rainfalls',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Raindays1mm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year of the weather data.', validators=[datasender.models.validate_year])),
                ('month', models.IntegerField(db_index=True, help_text='Month of the weather data (1-12).', validators=[datasender.models.validate_month])),
                ('value', models.FloatField(blank=True, help_text='Measured value for the weather metric.', null=True)),
            ],
            options={
                'verbose_name': 'Rain Days (1mm)',
                'verbose_name_plural': 'Rain Days (1mm)',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AirFrost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year of the weather data.', validators=[datasender.models.validate_year])),
                ('month', models.IntegerField(db_index=True, help_text='Month of the weather data (1-12).', validators=[datasender.models.validate_month])),
                ('value', models.FloatField(blank=True, help_text='Measured value for the weather metric.', null=True)),
            ],
            options={
                'verbose_name': 'Air Frost',
                'verbose_name_plural': 'Air Frosts',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
